<a href="https://colab.research.google.com/github/rajviishah/Real-Estate-Investment/blob/main/Clustering-Techniques/kMeans-GaussianMixtureModel-Yash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment 2**

The cleaning of this dataset has been done in the other colab added to this folder.

Importing all the necessary libraries.

In [ ]:
from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

mounting google drive.

In [ ]:
drive.mount("/content/drive")

Mounted at /content/drive

import cleaned data from drive using pandas

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/257/clean_train.csv")

df

      Unnamed: 0    Id  ...  SaleCondition_Normal  SaleCondition_Partial
0              0     1  ...                     1                      0
1              1     2  ...                     1                      0
2              2     3  ...                     1                      0
3              3     4  ...                     0                      0
4              4     5  ...                     1                      0
...          ...   ...  ...                   ...                    ...
1452        1455  1456  ...                     1                      0
1453        1456  1457  ...                     1                      0
1454        1457  1458  ...                     1                      0
1455        1458  1459  ...                     1                      0
1456        1459  1460  ...                     1                      0

[1457 rows x 223 columns]

In [ ]:
df = df.drop(['Unnamed: 0'], axis=1)

## **Kmeans**

K-means clustering is a simple learning algorithm that is used to solve clustering problems. It follows a simple procedure of classifying a given data set into a number of clusters, defined by the letter "k," which is fixed beforehand. The clusters are then positioned as points and all observations or data points are associated with the nearest cluster, computed, adjusted and then the process starts over using the new adjustments until a desired result is reached.

Reducing the dimensions of the data set using PCA.

In [ ]:
scaler =  StandardScaler()
scaler.fit(df)
scaled_data = scaler.transform(df)

pca = PCA(n_components = 2)
transformed_data = pca.fit_transform(scaled_data)

we can see that for 2 components only 25% of the variance is covered and we lose a lot of features.

In [ ]:
pca = PCA(n_components = 10)
transformed_data = pca.fit_transform(scaled_data)
np.cumsum(pca.explained_variance_ratio_ * 100)

array([ 6.38504329,  9.42111807, 12.0260809 , 14.19054574, 16.14543731,
       17.99112924, 19.74087716, 21.18839316, 22.61119399, 23.93560728])

Elbow Plot

The technique to determine K, the number of clusters.

In [ ]:
from sklearn.cluster import KMeans

wcss=[]
for i in range(1, 15):
    kmeans=KMeans(n_clusters = i)
    kmeans.fit(df)
    wcss.append(kmeans.inertia_)

plt.plot(range(1, 15), wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

lets visualise for k = 3

In [ ]:
kmeans = KMeans(n_clusters = 3)
y_predicted = kmeans.fit_predict(df)
y_predicted

In [ ]:
plt.figure(figsize=(8, 6))
plt.scatter(transformed_data[:, 0], transformed_data[:, 1], c=y_predicted)
plt.xlabel('PCA Feaure 1')
plt.ylabel('PCA Feature 2')

# **Gaussian Mixture**

A Gaussian Mixture is a function that is comprised of several Gaussians, each identified by k ∈ {1,…, K}, where K is the number of clusters of our dataset. Each Gaussian k in the mixture is comprised of the following parameters:
1. A mean that defines its centre.
2. A covariance that defines its width. This would be equivalent to the dimensions of an ellipsoid in a multivariate scenario.
3. A mixing probability that defines how big or small the Gaussian function will be.

Importing library.

In [ ]:
from sklearn.mixture import GaussianMixture

gmm = GaussianMixture(n_components = 3).fit(df)
labels = gmm.predict(df)
plt.scatter(df["TotalBsmtSF"], df["SalePrice"], c=labels, s=40, cmap='viridis')